server:
  port: 8080
  servlet:
    context-path: /zen8labs-system

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/banking}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "1lD9fsDTGBoeO+PtSfpBlE87zHJSoGWb1g3ptVl7qlfPEXCdXAw1NjhDlELjTIEX"
  valid-duration: 3600  # in second
  refreshable-duration: 360000  # in seconds

open:
  api:
    title: API document
    version: 1.0.0
    description: Banking System
    serverUrl: http://localhost:8080/zen8labs-system
    serverName: Server Test

twilio:
  account-sid: "AC5b8d0a13801f9246d201cf51149dd9eb"
  auth-token: "0488d6add408ecf9d51609583ddc07db"
  from-phone: "+12093182802"