server:
  port: 8080
  servlet:
    context-path: /zen8labs

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/banking'
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true